rules:
  
  oas-random-property:
    description: Random property should exist at the root
    message: Random property doesnt exist
    severity: warn
    given: $
    then:
      field: random
      function: defined
    
  oas-name-of-title:
    description: Random property should exist at the root
    message: Random property doesnt exist
    severity: warn
    given: $.info.apiname
    then:
      field: title
      function: defined
