rules:
  
  oas-random-property:
    description: Random property should exist at the root
    message: Random property doesnt exist
    severity: warn
    given: $
    then:
      field: random
      function: defined
    
  oas-title-of-apiname:
    description: apiname should have a title property.
    message: apiname doesn't have a title property
    severity: warn
    given: $.info.apiname
    then:
       field: title
       function: defined
