rules:

# print not working
  schema-types:
    description: enum response type
    message: '{{description}}'
    severity: info
    given: $.paths.*.*.responses.*.content.*.schema
    then:
      field: type
      function: enumeration
      functionOptions:
        values:
          - object
          - array
          - string
