name: Run Spectral Rules!

on:
  - workflow_dispatch
  - push
  - pull_request
    
jobs:
  build:
    name: API Checks
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      # Run Spectral
      - uses: stoplightio/spectral-action@v0.8.0
        with:
          file_glob: api*.yaml
          spectral_ruleset: .spectral.yaml
